<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Litipk\\BigNumbers\\' => array($vendorDir . '/litipk/php-bignumbers/src'),
);
