<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'XPDF' => array($vendorDir . '/php-xpdf/php-xpdf/src'),
    'Symfony\\Component\\Process\\' => array($vendorDir . '/symfony/process'),
    'Psr\\Log\\' => array($vendorDir . '/psr/log'),
    'Evenement' => array($vendorDir . '/evenement/evenement/src'),
    'Alchemy' => array($vendorDir . '/alchemy/binary-driver/src'),
);
